// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Reservation } from "./Reservation";

/**
 * Ce que le bloc de capture montre pendant qu'on tape.
 *
 * Il est rendu par le backend et non calculé dans la webview pour la même raison que le
 * reste : les glyphes, la règle du modificateur et la table des réservées sont ici.
 */
export type CapturePreview = { 
/**
 * La combinaison frappée, en glyphes — vide si elle n'en fait pas une.
 */
keys: string, 
/**
 * Elle peut être confirmée par `⏎`.
 */
accepted: boolean, 
/**
 * Pourquoi elle ne peut pas l'être, le cas échéant.
 */
why: string | null, 
/**
 * L'avertissement de la planche — **jamais** un refus.
 */
reservation: Reservation | null, };
