// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Le `match` d'un `[[command]]` : **un nom de processus**, et rien d'autre.
 *
 * La règle — non vide, ni espace, ni barre oblique — n'est pas une coquetterie de saisie.
 * La sonde d'[ADR-0005](../../../../docs/adr/0005-sonde-cwd-libproc.md) lit le nom du
 * processus en avant-plan, et [ADR-0006](../../../../docs/adr/0006-decouverte-automatique-des-agents.md)
 * le **compare** à ce que les réglages déclarent. Un chemin ou une ligne de commande ne
 * correspondrait donc jamais à rien, tout en se lisant comme une entrée valide : l'outil
 * paraîtrait déclaré et ne serait jamais reconnu.
 *
 * C'est aussi la **frontière de sécurité du test 3** : le nom est ce que
 * [`CommandRunner::locate`](super::CommandRunner::locate) cherche dans le `PATH`, et un
 * chemin déguisé en nom ferait sortir la résolution du `PATH` pour exécuter un fichier
 * désigné à la main dans un champ de réglages. Le port prend un `Command`, donc la
 * question ne se repose plus à l'autre bout.
 *
 * **[`Command::parse`] est le seul constructeur de production.** C'est ce qui fait qu'une
 * commande Tauri de plus — il en arrive à chaque tranche — ne peut pas passer à côté de la
 * règle sans que le compilateur le dise.
 *
 * Sérialisé **transparent** : sur le fil c'est une chaîne, exactement comme avant.
 *
 * `ts(as = "String")` dit la même chose au générateur de types : le `Command.ts` produit est
 * `export type Command = string`, donc **structurellement une chaîne** — les interfaces
 * écrites à la main qui déclarent `command: string` continuent de correspondre. Sans cet
 * attribut, `ts-rs` refuse de compiler la forme qui contient un `Command`, faute de savoir
 * quoi en dire.
 */
export type Command = string;
