// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ce qu'il est advenu d'une demande de composition.
 */
export type ComposeOutcome = "written" | "queued" | "prompt-not-empty" | "no-agent";
