// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * L'issue choisie devant un conflit. Deux, nommées, et pas de troisième silencieuse.
 */
export type ConflictChoice = "give" | "keep";
