// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Le dossier qu'une entrée vise, sous **ses deux formes**.
 *
 * « Quel dossier cette entrée vise-t-elle réellement ? » se répondait de trois façons, et
 * il existe deux écritures du même dossier : celle que l'utilisateur a tapée (`~/.claude`)
 * et celle qui touche le disque (`/Users/moi/.claude`). Quatre mécanismes dépendent de
 * leur accord — la vérification, la détection de doublon, la recherche du bloc de hooks, et
 * la mémoire du dernier dossier valide. **Si l'un comparait les formes brutes et un autre
 * les formes résolues, la bannière de doublon mentirait** : `~/.claude` et
 * `/Users/moi/.claude` ne se verraient pas.
 *
 * Les deux formes voyagent donc ensemble, et l'**égalité porte sur la forme résolue** :
 * deux cibles sont la même cible quand elles désignent le même dossier, quoi que
 * l'utilisateur ait tapé. Il n'y a plus qu'une notion de « même dossier » dans la feature,
 * donc plus rien à faire diverger.
 *
 * **[`Verifier::target`](super::Verifier::target) est le seul producteur de production**,
 * parce qu'il est le seul à connaître le profil de l'adaptateur — donc le seul à pouvoir
 * répondre « l'entrée, sinon le défaut de l'adaptateur ».
 *
 * Sérialisé comme **la forme déclarée**, une chaîne : c'est ce que la fenêtre affiche dans
 * son champ de chemin, et le contrat sur le fil ne bouge pas d'un caractère.
 *
 * `ts(as = "String")` dit la même chose au générateur de types, et ici l'attribut fait plus
 * que débloquer la compilation : dérivé nu, `ts-rs` annoncerait au TypeScript les **deux**
 * champs de la structure, alors que le `Serialize` manuel n'en écrit qu'un — le type généré
 * décrirait une forme que le fil ne porte pas. Avec lui, `ConfigTarget.ts` est
 * `export type ConfigTarget = string`, qui est exactement ce qui traverse.
 */
export type ConfigTarget = string;
