// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ce qu'`apply` change dans l'entrée — et rien d'autre ne change jamais.
 */
export type FixAction = { "kind": "useAdapter", adapter: string, } | { "kind": "useFolder", path: string, };
