// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * L'outil sur lequel la fenêtre de réglages doit s'ouvrir, tant qu'elle ne l'a pas lu.
 *
 * **Une demande, jamais une écriture** : elle nomme l'outil que le marqueur de la sidebar
 * désigne, et l'écran décide quoi en montrer. Rien n'est écrit chez l'utilisateur avant son
 * geste dans cette fenêtre (ADR-0007).
 *
 * Elle est *retenue* et pas seulement émise parce que la fenêtre est **créée** par le même
 * geste : un event parti avant que la page n'existe n'aurait aucun abonné. La page vient
 * donc la chercher en s'affichant, et l'event ne sert qu'au cas où elle était déjà ouverte.
 */
export type FocusedTool = { command: string, adapter: string, };
