// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * La taille de police du terminal, en points.
 *
 * **C'est un réglage de l'application, pas d'onglet**, et c'est la décision de cette
 * feature — pas un défaut subi. [ADR-0003](../../../../docs/adr/0003-zone-terminal-unique.md)
 * dit qu'un onglet porte au plus un PTY ; elle ne dit pas qu'il porte une apparence. Un
 * émulateur de terminal traite la taille comme une préférence de confort de lecture, qui
 * suit l'utilisateur d'un onglet à l'autre : la régler par onglet obligerait à la régler
 * à chaque `Cmd+N`, et donnerait à la fenêtre de réglages une valeur qu'elle ne saurait
 * pas nommer — « la taille » n'existerait plus. Elle vit donc ici, à côté du mode de
 * thème, avec les autres préférences d'apparence de la fenêtre.
 *
 * **Bornée, et par construction.** Les deux bornes ne sont pas un garde-fou d'interface
 * mais une propriété du type : rien ne peut fabriquer une taille hors de `MIN..=MAX`, pas
 * même un `~/.ash/theme.json` édité à la main — la relecture ramène dans l'intervalle
 * plutôt que de refuser le fichier. Un terminal à 2 points ne se répare pas au clavier,
 * puisqu'on ne voit plus ce qu'on tape.
 */
export type FontSize = number;
