// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HookAction } from "./HookAction";
import type { HookChoice } from "./HookChoice";
import type { HookState } from "./HookState";

/**
 * Ce que la ligne `hooks` d'une entrée affiche, et ce qu'elle laisse faire.
 *
 * Elle voyage **avec** la déclaration, comme la vérification, et pour la même raison : une
 * entrée dont le chemin change change d'état de hooks au même instant, et deux tables
 * séparées laisseraient un intervalle où l'écran montrerait l'un sous l'autre.
 */
export type HooksReport = { state: HookState, 
/**
 * La phrase de la ligne — `installed · v1`, `no ash hooks in this file`…
 */
summary: string, 
/**
 * Les deux lignes de prose sous la ligne : **la conséquence**, pas la répétition.
 */
note: string, 
/**
 * Le fichier concerné, quand il y en a un.
 */
file: string | null, action: HookAction, 
/**
 * Le bouton est-il allumé ? Il reste **visible** dans tous les cas.
 */
enabled: boolean, 
/**
 * Ce que le diff propose de trancher, dans l'ordre. Vide quand rien ne s'écrit.
 */
choices: Array<HookChoice>, 
/**
 * Le diff de ce qu'Ash écrirait, sur le fichier **tel qu'il est**, avant toute
 * écriture. `None` quand il n'y a rien à écrire, ou rien à lire.
 */
diff: string | null, 
/**
 * La copie qui sera prise **avant** l'action, annoncée avant et non après (§4.2).
 */
backup: string | null, };
