// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ce qu'un bouton de la ligne — ou du diff — déclenche.
 */
export type HookAction = "install" | "update" | "remove" | "seeTheDiff";
