// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ce qui était attendu, et ce qui a été trouvé.
 */
export type Mismatch = { expected: string, found: string, };
