// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ce que le formulaire d'ajout envoie — du texte brut, pas encore une déclaration.
 *
 * Distinct de [`ToolDeclaration`] parce que les deux n'ont pas les mêmes invariants : ici
 * tout est possible, y compris des espaces autour et un adaptateur qui n'existe pas.
 * [`NewTool::declare`] est le seul passage de l'un à l'autre.
 */
export type NewTool = { command: string, label: string | null, adapter: string, config: string | null, };
