// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ce que macOS laisse savoir à Ash de sa propre autorisation.
 */
export type NotificationPermission = "granted" | "denied" | "undisclosed";
