// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NotificationPermission } from "./NotificationPermission";
import type { NotificationSwitch } from "./NotificationSwitch";

/**
 * La section `notifications` de la fenêtre, en entier.
 */
export type NotificationsReport = { permission: NotificationPermission, 
/**
 * La phrase de la ligne d'état.
 */
summary: string, 
/**
 * Sa conséquence, en prose : ce que l'état coûte à l'utilisateur.
 */
note: string, 
/**
 * Le chemin où l'accorder. Toujours présent — il vaut aussi pour vérifier un « oui ».
 */
path: string, 
/**
 * Les trois interrupteurs de la spec §9, dans l'ordre de la spec §8.
 *
 * Ils voyagent depuis le backend plutôt que d'être écrits dans la vue : ce sont eux qui
 * décident d'une bannière, et une liste recopiée finirait par offrir un interrupteur qui
 * ne commande rien — ou par en cacher un qui commande encore.
 */
switches: Array<NotificationSwitch>, };
