// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationKind } from "./OperationKind";
import type { Progress } from "./Progress";

/**
 * L'opération git en cours dans ce worktree.
 *
 * Elle est **propre au worktree** : deux worktrees du même dépôt peuvent avoir un rebase
 * dans l'un et rien dans l'autre ([ADR-0012](../../../../docs/adr/0012-worktree-unite-de-travail.md)).
 * C'est pourquoi elle se lit dans le dossier git du worktree, pas dans le dépôt commun.
 */
export type Operation = { kind: OperationKind, 
/**
 * La branche que l'opération déplace (`refs/heads/feat` → `feat`), quand git la nomme.
 */
branch: string | null, 
/**
 * Le point d'arrivée : un nom de branche quand un ref le désigne, l'identifiant
 * abrégé sinon. C'est le `main` de `rebasing onto main`.
 */
onto: string | null, 
/**
 * Où en est l'opération. Absente pour un merge, qui n'a pas d'étapes.
 */
progress: Progress | null, };
