// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ce qu'un fichier est devenu.
 *
 * Quatre issues et non un booléen : « rien à retirer » n'est pas « retiré », et un fichier
 * que le disque a refusé n'est ni l'un ni l'autre. Les confondre ferait rapporter une
 * désinstallation complète là où un fichier porte encore le marqueur d'Ash.
 */
export type Outcome = { "kind": "removed" } | { "kind": "removedTheFile" } | { "kind": "nothingLeft" } | { "kind": "refused", why: string, };
