// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Le dépôt commun sous lequel une ligne épinglée se range.
 *
 * Même forme que le `RepoRef` de `features::pty`, et **pas** le même type : une feature
 * n'importe pas l'intérieur d'une autre, et un onglet et une épingle n'ont aucune raison de
 * partager une structure parce qu'elles se ressemblent aujourd'hui. Le côté TypeScript, lui,
 * n'écrit qu'une interface et vérifie qu'elle reflète les deux (`shared/ipc/mirror.ts`).
 */
export type PinnedRepo = { 
/**
 * Le dossier git commun : c'est par lui que la sidebar groupe, jamais par le nom.
 */
id: string, name: string, };
