// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ce qu'un retrait emporterait dans un fichier.
 */
export type PlannedRemoval = { file: string, 
/**
 * Les entrées déclarées qui visent ce fichier — deux comptes peuvent le partager.
 */
commands: Array<string>, 
/**
 * Le nombre d'entrées marquées qui partiraient.
 */
entries: number, 
/**
 * Le fichier ne portait que ça : il s'en va avec elles (spec §10).
 */
deletesTheFile: boolean, 
/**
 * Une main est passée sur une entrée d'Ash dans ce fichier.
 */
handEdited: boolean, 
/**
 * Le fichier tel qu'il est, face à ce qu'Ash laisserait.
 */
diff: string, };
