// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `2/5` : l'étape en cours et le total.
 */
export type Progress = { step: number, total: number, };
