// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ce que le PTY envoie à la webview.
 */
export type PtyFrame = { "kind": "chunk", data: string, } | { "kind": "exit", code: number | null, };
