// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlannedRemoval } from "./PlannedRemoval";

/**
 * Ce qu'un retrait complet ferait, fichier par fichier — **avant** de le faire.
 */
export type RemovalPlan = { 
/**
 * Les fichiers qui portent des entrées d'Ash, dans l'ordre des entrées déclarées.
 *
 * Un fichier où il n'y a rien à retirer **n'y figure pas** : nommer un fichier pour
 * dire qu'on n'y touchera pas ferait craindre l'inverse.
 */
files: Array<PlannedRemoval>, 
/**
 * La phrase du bouton — `5 entries in 1 file`, `nothing to remove`.
 */
summary: string, 
/**
 * Une main est passée sur une entrée d'Ash, quelque part.
 *
 * Remonté au plan entier parce que c'est ce qui change la nature du geste : il ne
 * reprend plus seulement ce qu'Ash a écrit, il emporte ce que quelqu'un en a fait.
 */
handEdited: boolean, 
/**
 * Ce que le geste ne touchera pas — voir [`KEPT`].
 */
kept: Array<string>, };
