// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Qui prend la combinaison avant Ash.
 *
 * Les deux cas ne se valent pas, et c'est pourquoi ils ne sont pas un seul booléen :
 * macOS prend la touche **toujours**, le terminal seulement quand c'est lui qu'on tape.
 */
export type ReservedBy = "macos" | "terminal";
