// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Reservation } from "./Reservation";

/**
 * Une ligne de la section `shortcuts` (spec §4.4, planche `3j`).
 */
export type ShortcutRow = { 
/**
 * L'identifiant de l'action — ce que la capture renvoie au backend.
 */
action: string, 
/**
 * Le sous-menu où l'action vit : c'est ce qui **groupe** la liste.
 */
group: string, label: string, 
/**
 * La combinaison, écrite comme macOS l'écrit — `⇧⌘T`, `⌃⇥`, `⌘+`. Vide quand la ligne
 * n'a **aucun** raccourci : c'est l'état que `⌫` produit.
 */
keys: string, 
/**
 * Ce que `back to default` rendrait. Vide si le défaut est « aucun raccourci ».
 */
defaultKeys: string, 
/**
 * La ligne a été changée : c'est elle qui porte l'icône de retour, et elle seule.
 */
changed: boolean, 
/**
 * Cette ligne s'ouvre en capture. Faux pour la famille des positions d'onglet.
 */
rebindable: boolean, 
/**
 * Ce qui prend la combinaison avant Ash, s'il y a quelqu'un.
 */
reservation: Reservation | null, };
