// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Les deux lignes d'un conflit, et la ou les issues qui le referment.
 *
 * Il naît d'une capture qui viserait une combinaison déjà prise, et **rien n'est appliqué
 * tant qu'il vit** : c'est la règle de la planche, « ash ne réattribue jamais en silence ».
 *
 * Il a **deux formes**, et ce qui les distingue est son détenteur (issue #137) :
 * une ligne réglable peut céder sa combinaison, la famille des positions d'onglet ne le peut
 * pas. La seconde forme est donc un **refus** : les deux mêmes lignes, un diagnostic qui dit
 * pourquoi c'est sans appel, et **pas** de `give` — voir [`Held`].
 */
export type ShortcutConflict = { 
/**
 * La combinaison disputée, en glyphes — et écrite comme elle a été **pressée** : `⌘&`
 * sur un clavier français, là où la liaison, elle, se lit `⌘1`. Le bloc répond à une
 * frappe, donc il parle de la touche qui est sous les doigts.
 */
keys: string, 
/**
 * L'action qui détient la combinaison — la ligne `already assigned`.
 */
holder: string, holderLabel: string, 
/**
 * L'action qui vient de la capturer — la ligne `just now`.
 */
asked: string, askedLabel: string, 
/**
 * Le diagnostic, sous le filet : `two actions on ⌘X — the last one set would silently
 * win`.
 */
diagnosis: string, 
/**
 * Le libellé de l'issue conséquente — `give ⌘X to New Tab`.
 *
 * **Absent quand le détenteur ne peut pas céder** : la famille `Tab 1 … Tab 9` n'est pas
 * réglable, donc lui reprendre `⌘1` ne tiendrait pas une session — la relecture du
 * fichier le lui rendrait au démarrage suivant. Le bloc n'est alors plus un choix, c'est
 * un refus, et il n'offre que `keep`.
 */
give: string | null, 
/**
 * Le libellé de l'issue secondaire — `keep the old one`. Seule issue d'un refus.
 */
keep: string, };
