// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * La largeur de la colonne dépliée, en pixels.
 *
 * **En pixels, et non en fraction de fenêtre**, parce que c'est ce que la personne a réglé :
 * une colonne posée à 300 px doit rester à 300 px quand on agrandit la fenêtre, comme dans
 * tout logiciel à colonnes. Les bornes, elles, sont bien relatives — de 10 % à 80 % de la
 * fenêtre — mais ce sont des bornes de **mise en page**, qui dépendent d'un viewport que
 * seule la webview connaît : elles vivent donc dans `src/features/sidebar/resize.ts`, avec
 * la règle qui les applique à chaque rendu.
 *
 * Les deux bornes ci-dessous ne sont pas ces bornes-là. Elles ne servent qu'à ce qu'un
 * `~/.ash/theme.json` édité à la main — ou écrit par une version d'Ash à venir — ne rende
 * jamais un nombre absurde, et elles sont délibérément **plus larges** que tout ce que le
 * clamp relatif peut produire : si elles mordaient sur lui, la largeur montrée et la largeur
 * gardée se contrediraient jusqu'au redémarrage suivant.
 */
export type SidebarWidth = number;
