// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TreeStatus } from "./TreeStatus";
import type { Upstream } from "./Upstream";

/**
 * L'état d'un worktree tel que `git status --porcelain=v2 --branch` le décrit.
 *
 * Les deux moitiés viennent du **même** appel : les compter séparément coûterait deux
 * processus pour une seule ligne d'affichage.
 */
export type Status = { tree: TreeStatus, 
/**
 * La comparaison avec la branche amont. `None` quand la branche n'en suit aucune —
 * une branche locale toute neuve, ou un `HEAD` détaché.
 */
upstream: Upstream | null, 
/**
 * Les chemins qui attendent une décision, tels que git les écrit.
 *
 * Ils viennent du **même** appel que le reste (spec §7.4 a besoin des chemins, pas
 * seulement de leur nombre), et c'est ce qui évite un second verbe git : les lignes
 * `u` de `--porcelain=v2` les portent déjà. La liste est bornée par
 * [`super::porcelain`] ; `tree.conflicted`, lui, ne l'est pas.
 */
conflicts: Array<string>, };
