// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FixAction } from "./FixAction";

/**
 * Ce qu'on propose de faire, quand quelque chose a une chance de marcher.
 *
 * `None` est un cas normal et non un manque : quand rien de ce qu'Ash sait faire ne peut
 * aider, proposer quand même une action serait un conseil générique — exactement ce que le
 * critère d'acceptation refuse. La question, elle, est toujours là.
 */
export type SuggestedFix = { 
/**
 * La question posée à l'utilisateur, telle qu'elle s'affiche.
 */
question: string, 
/**
 * Ce que le bouton `apply` ferait, ou `None` s'il n'y a rien à appliquer.
 */
apply: FixAction | null, };
