// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentState } from "./AgentState";
import type { RecognizedAgent } from "./RecognizedAgent";
import type { Subagent } from "./Subagent";
import type { TabLocation } from "./TabLocation";

/**
 * Ce qu'un onglet montre de lui-même au frontend.
 *
 * C'est aussi ce que la boucle de sonde annonce quand un onglet a **bougé** : un même
 * type pour la liste et pour l'event, parce que rien ne justifie que le frontend
 * apprenne un onglet de deux façons différentes. Un onglet posé à son invite ne traverse
 * pas la frontière — voir [`PtyRegistry::changes`].
 */
export type TabInfo = { tabId: string, 
/**
 * Le répertoire **courant** de l'onglet, sondé à la demande.
 *
 * C'est lui que « nouvel onglet dans le worktree courant » (spec §4.4) reprend : le
 * répertoire où l'onglet en est, pas celui d'où il est parti.
 */
cwd: string, 
/**
 * Le programme qui tient l'avant-plan — le nom que la sidebar et la barre affichent.
 *
 * C'est le nom de **l'outil** quand il en est un : un Claude Code posé par son
 * installateur officiel tourne sous un exécutable nommé `2.1.234`, et l'onglet doit
 * dire `claude` — aujourd'hui comme après la mise à jour suivante
 * ([ADR-0006](../../../../docs/adr/0006-decouverte-automatique-des-agents.md)).
 */
process: string, 
/**
 * L'outil reconnu dans l'avant-plan, et ce que sa configuration porte. `None` pour un
 * shell à son invite comme pour un `vim`.
 *
 * Il ne bouge **pas** d'une passe de sonde à l'autre tant que le même programme tient
 * l'avant-plan : la fiche est comparée entière pour décider d'émettre (voir
 * [`Self::state_since`]), et un champ qui changerait toutes les 300 ms réveillerait la
 * sidebar entière en permanence.
 *
 * Il ne porte **aucun état d'agent** : reconnaître un outil n'est pas savoir ce qu'il
 * fait ([ADR-0007](../../../../docs/adr/0007-etats-par-hooks.md)). Ce qu'il dit en plus
 * du nom, c'est si la configuration de l'outil porte le marqueur d'Ash — donc pourquoi
 * cet onglet ne montrera jamais `waiting` tant qu'elle ne le porte pas.
 */
agent: RecognizedAgent | null, state: AgentState, 
/**
 * Quand l'onglet est **entré** dans cet état, en millisecondes depuis l'époque Unix.
 *
 * Une date, jamais une durée, et c'est ce qui garde cette fiche **stable** : le
 * registre compare le `TabInfo` entier pour décider s'il faut annoncer quoi que ce
 * soit (voir [`Self::changes`]). Une durée vivante ferait donc changer la fiche de
 * chaque onglet actif à chaque seconde, et l'event ponctuel deviendrait un flux — on
 * paierait un rendu complet de la sidebar par seconde pour animer un compteur.
 *
 * Le `working · 15m22s` de la maquette se calcule donc à l'affichage, à partir de
 * cette date et de l'horloge du frontend.
 *
 * **`number` et non `bigint`** : `ts-rs` prête un `bigint` à tout `u64`, par prudence
 * sur les valeurs qui dépassent 2⁵³. Ce ne serait pas seulement pénible — ce serait
 * faux : `serde_json` écrit un nombre JSON, que la webview lit en `number`, et un
 * `bigint` déclaré ici mentirait sur ce qui arrive vraiment. La borne de 2⁵³
 * millisecondes tombe en l'an 287396.
 */
stateSince: number, 
/**
 * Les sous-agents qui tournent **dans** cet onglet, en ce moment (spec §6.5).
 *
 * Vide dans le cas courant, et vide pour toujours chez un outil qui n'expose pas ses
 * sous-tâches. Ils voyagent avec l'onglet et non par un event à eux : ce sont des lignes
 * filles de la sienne, elles n'ont pas de terminal
 * ([ADR-0003](../../../../docs/adr/0003-zone-terminal-unique.md)) et rien ne les
 * sélectionne.
 *
 * Chacun porte sa **date d'entrée**, pour la même raison que [`Self::state_since`] : une
 * durée vivante ferait changer cette fiche à chaque seconde, et l'event ponctuel
 * deviendrait un flux.
 */
subagents: Array<Subagent>, 
/**
 * Où cet onglet se range dans la hiérarchie d'ADR-0012. `None` quand le répertoire
 * n'a pas pu être situé.
 */
location: TabLocation | null, };
