// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RepoRef } from "./RepoRef";

/**
 * La localisation d'un onglet, telle qu'elle traverse la frontière.
 *
 * `repo` à `None` **est** la forme à plat d'ADR-0012 : un dépôt sans worktree lié, ou un
 * répertoire hors de tout dépôt. Le frontend n'a rien à en déduire — il rend un niveau ou
 * deux selon que ce champ est là.
 */
export type TabLocation = { 
/**
 * La racine du worktree. C'est la clé de groupement des onglets.
 */
worktreeRoot: string, 
/**
 * Le nom **brut** du dossier du worktree — la matière du suffixe `·sidebar`.
 */
worktreeName: string, repo: RepoRef | null, };
