// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * L'état d'une pastille de la rangée.
 *
 * [`TestOutcome::Pending`] et [`TestOutcome::Skipped`] disent tous deux « pas lancé », et
 * ne se peignent pourtant pas pareil : le premier attend, le second ne viendra jamais
 * parce que la chaîne s'est arrêtée avant lui.
 */
export type TestOutcome = "pending" | "running" | "passed" | "warned" | "failed" | "skipped";
