// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Un des quatre tests, tel que la fenêtre l'annonce.
 *
 * Les libellés voyagent **du backend vers l'écran**, et ne sont pas écrits des deux côtés :
 * c'est ici que les tests existent, donc c'est ici qu'ils se nomment. Une liste recopiée
 * dans la vue finirait par décrire un test que la séquence ne lance plus.
 */
export type TestDescription = { number: number, 
/**
 * Le libellé long — `the folder exists and is readable`.
 */
label: string, 
/**
 * Le libellé court de la note de barème — `folder readable`.
 */
shortLabel: string, 
/**
 * Son échec invalide-t-il l'entrée, ou la réserve-t-il seulement ?
 */
decisive: boolean, };
