// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `+3 ~1` : des **nombres de fichiers**, jamais de lignes.
 *
 * La maquette n'en affiche que deux ; les quatre sont là parce qu'ils viennent du même
 * appel et qu'ils disent des choses différentes. Ce qui s'affiche est l'affaire de la
 * ligne de statut, pas du backend.
 */
export type TreeStatus = { 
/**
 * Fichiers ajoutés à l'index, **et** fichiers non suivis : le `+` de la maquette.
 */
added: number, 
/**
 * Fichiers modifiés, renommés ou copiés : le `~`.
 */
modified: number, 
/**
 * Fichiers supprimés. Pas dans la maquette, mais dans le modèle : le savoir sans
 * l'afficher coûte zéro, le redemander plus tard coûterait un appel de plus.
 */
deleted: number, 
/**
 * Fichiers en conflit — un merge ou un rebase arrêté attend une décision dessus.
 */
conflicted: number, };
