// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `↑2 ↓1` : l'avance et le retard sur la branche amont.
 */
export type Upstream = { ahead: number, behind: number, };
