// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Mismatch } from "./Mismatch";
import type { SuggestedFix } from "./SuggestedFix";
import type { TestOutcome } from "./TestOutcome";
import type { VerificationState } from "./VerificationState";

/**
 * Ce qu'une entrée a prouvé, à un instant donné.
 *
 * Une seule structure pour les cinq états plutôt qu'une énumération de formes : la
 * rangée de pastilles et la phrase existent dans les cinq cas, et la fenêtre les dessine
 * sans se demander lequel elle a sous la main.
 */
export type Verification = { state: VerificationState, 
/**
 * Les quatre pastilles, dans l'ordre de [`ToolTest::ALL`].
 */
tests: Array<TestOutcome>, 
/**
 * La phrase de la ligne `test`.
 */
summary: string, 
/**
 * `stopped at test <n>` — présent seulement quand la chaîne s'est arrêtée.
 */
stoppedAt: number | null, detail: Mismatch | null, fix: SuggestedFix | null, 
/**
 * La commande réellement lancée, montrée pendant l'attente du test 4.
 */
launched: string | null, 
/**
 * Les hooks peuvent-ils être écrits ?
 *
 * **Calculé ici et transporté tel quel**, jamais recalculé côté fenêtre : c'est la
 * règle qui décide d'écrire dans un fichier de l'utilisateur, et elle n'a qu'un
 * propriétaire. La fenêtre l'annonce, elle ne la rejoue pas
 * ([ADR-0009](../../../../docs/adr/0009-cycle-de-vie-des-agents.md)).
 */
allowsHooks: boolean, };
