// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Les cinq états de la maquette §3.4, et rien de plus.
 */
export type VerificationState = "unverified" | "verifying" | "valid" | "caveat" | "invalid";
