// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Head } from "./Head";
import type { Operation } from "./Operation";
import type { Status } from "./Status";

/**
 * Ce que la ligne de statut et la sidebar affichent d'un worktree.
 */
export type WorktreeMetadata = { head: Head, 
/**
 * L'opération git en cours, quand il y en a une. C'est elle qui l'emporte à
 * l'affichage : pendant un rebase, `HEAD` est détaché et ne dit plus rien d'utile.
 */
operation: Operation | null, 
/**
 * Ce que seul `git status` sait dire, quand il a pu le dire.
 *
 * `None` n'est pas une erreur : c'est « on ne sait pas encore », et ça se rend en
 * n'affichant ni `+3 ~1` ni `↑2 ↓1`. Le reste de la ligne, lui, est toujours là.
 */
status: Status | null, };
